section1:

  experiment1:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment2:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment3:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment4:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 128

  experiment5:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment6:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment7:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment8:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 128

  experiment9:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment10:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment11:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment12:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "rgb"
    quantization_interval: 128

section2:

  experiment1:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment2:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment3:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment4:
    query_number: 1
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 128

  experiment5:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment6:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment7:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment8:
    query_number: 2
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 128

  experiment9:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment10:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment11:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment12:
    query_number: 3
    grid_n: 1
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 128

section3:

  experiment1:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 8

  experiment2:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment3:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment4:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment5:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 128

  experiment6:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 8

  experiment7:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment8:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment9:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment10:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 128

  experiment11:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 8

  experiment12:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 16

  experiment13:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 32

  experiment14:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 64

  experiment15:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "rgb"
    quantization_interval: 128

section4:

  experiment1:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment2:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment3:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment4:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment5:
    query_number: 1
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 128

  experiment6:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment7:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment8:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment9:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment10:
    query_number: 2
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 128

  experiment11:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment12:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 16

  experiment13:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 32

  experiment14:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment15:
    query_number: 3
    grid_n: 1
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 128

section5:

  experiment1:
      query_number: 1
      grid_n: 2
      color_histogram_type: "3d"
      color_space_type: "hsv"
      quantization_interval: 64

  experiment2:
    query_number: 1
    grid_n: 4
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment3:
    query_number: 1
    grid_n: 6
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment4:
    query_number: 1
    grid_n: 8
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment5:
    query_number: 1
    grid_n: 2
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment6:
    query_number: 1
    grid_n: 4
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment7:
    query_number: 1
    grid_n: 6
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment8:
    query_number: 1
    grid_n: 8
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

section6:

  experiment1:
    query_number: 2
    grid_n: 2
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment2:
    query_number: 2
    grid_n: 4
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment3:
    query_number: 2
    grid_n: 6
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment4:
    query_number: 2
    grid_n: 8
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment5:
    query_number: 2
    grid_n: 2
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment6:
    query_number: 2
    grid_n: 4
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment7:
    query_number: 2
    grid_n: 6
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment8:
    query_number: 2
    grid_n: 8
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

section7:

  experiment1:
    query_number: 3
    grid_n: 2
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment2:
    query_number: 3
    grid_n: 4
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment3:
    query_number: 3
    grid_n: 6
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment4:
    query_number: 3
    grid_n: 8
    color_histogram_type: "3d"
    color_space_type: "hsv"
    quantization_interval: 64

  experiment5:
    query_number: 3
    grid_n: 2
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment6:
    query_number: 3
    grid_n: 4
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment7:
    query_number: 3
    grid_n: 6
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8

  experiment8:
    query_number: 3
    grid_n: 8
    color_histogram_type: "per-channel"
    color_space_type: "hsv"
    quantization_interval: 8